// Wire Protocol Manifest
//
// Generated by scripts/gen-wire-manifest.mts — do not edit by hand.
// Regenerate with: bun --filter @moonshot-ai/agent-core-v2 gen:wire-manifest
//
// protocol_version: "1.5" (migrations: )
//
// One declaration per record type registered via defineOp(...) and drained from
// the runtime OP_REGISTRY. Every payload declaration carries its record type in
// a `_name` field. Payload sketches use TypeScript type syntax; when a
// named type is expanded inline, its name appears as a doc comment
// (`/** ContextMessage */`). Bare type names (ContentPart, ContextMessage, …)
// refer to the real types in src/ — they are intentionally not resolved here.
// `// …` marks a capped field list. On disk (wire.jsonl) the journal opens with
// a metadata line {"type": "metadata", "protocol_version", "created_at"}; each
// op record is {"type", ...payload, "time"} — object payloads spread at the
// top level, scalar payloads nest under a "payload" key.
//
// Declaration flags: persisted (written to the journal; absent = transient),
// toEvent (also publishes an IEventBus fact on live dispatch), blobs (the
// owning model offloads inline media to blob storage), cross-reducers
// (foreign models that also reduce this record on dispatch and replay).

// Index (48 record types)
//   config.update                      profile               persisted  (unresolved)
//   context.append_loop_event          contextMemory         persisted  (unresolved)
//   context.append_message             contextMemory         persisted  (unresolved)
//   context.apply_compaction           contextMemory         persisted  (unresolved)
//   context.clear                      contextMemory         persisted  (unresolved)
//   context.undo                       contextMemory         persisted  (unresolved)
//   cron.add                           cron                  transient  (unresolved)
//   cron.cursor                        cron                  transient  (unresolved)
//   cron.delete                        cron                  transient  (unresolved)
//   forked                             goal                  persisted  (unresolved)
//   full_compaction.begin              fullCompaction        persisted  (unresolved)
//   full_compaction.cancel             fullCompaction        persisted  (unresolved)
//   full_compaction.complete           fullCompaction        persisted  (unresolved)
//   goal.clear                         goal                  persisted  (unresolved)
//   goal.create                        goal                  persisted  (unresolved)
//   goal.update                        goal                  persisted  (unresolved)
//   interaction.request                interaction           persisted  (unresolved)
//   interaction.resolved               interaction           persisted  (unresolved)
//   interruptionReminder.recorded      interruptionReminder  persisted  (unresolved)
//   llm.request                        llm.requestTrace      persisted  (unresolved)
//   llm.tools_snapshot                 llm.requestTrace      persisted  (unresolved)
//   mcp.tools_discovered               mcp.discovery         persisted  (unresolved)
//   permission.record_approval_result  permissionRules       persisted  (unresolved)
//   permission.rules.add               permissionRules       transient  (unresolved)
//   permission.set_mode                permissionMode        persisted  (unresolved)
//   plan_mode.cancel                   plan                  persisted  (unresolved)
//   plan_mode.enter                    plan                  persisted  (unresolved)
//   plan_mode.exit                     plan                  persisted  (unresolved)
//   plan.revision                      plan                  persisted  (unresolved)
//   profile.bind                       profile               persisted  (unresolved)
//   skill.activate                     skill                 transient  (unresolved)
//   swarm_mode.enter                   swarm                 persisted  (unresolved)
//   swarm_mode.exit                    swarm                 persisted  (unresolved)
//   task.started                       task                  persisted  (unresolved)
//   task.terminated                    task                  persisted  (unresolved)
//   token_counting.measured            tokenCounting         transient  (unresolved)
//   token_counting.rebased             tokenCounting         transient  (unresolved)
//   token_counting.truncated           tokenCounting         transient  (unresolved)
//   tools.register_user_tool           userTool              persisted  (unresolved)
//   tools.reset_active_tools           profile.activeTools   persisted  (unresolved)
//   tools.set_active_tools             profile.activeTools   persisted  (unresolved)
//   tools.unregister_user_tool         userTool              persisted  (unresolved)
//   tools.update_store                 todo                  persisted  (unresolved)
//   turn.cancel                        turn                  persisted  (unresolved)
//   turn.ended                         turn                  persisted  (unresolved)
//   turn.prompt                        turn                  persisted  (unresolved)
//   turn.steer                         turn                  persisted  (unresolved)
//   usage.record                       usage                 persisted  (unresolved)

/**
 * model: profile · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ConfigUpdatePayload {
  _name: 'config.update';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: turn
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ContextAppendLoopEventPayload {
  _name: 'context.append_loop_event';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice, task.notificationDelivery, todo
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ContextAppendMessagePayload {
  _name: 'context.append_message';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, task.notificationDelivery, todo
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ContextApplyCompactionPayload {
  _name: 'context.apply_compaction';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, task.notificationDelivery, todo
 * owner: (unresolved)
 */
interface ContextClearPayload {
  _name: 'context.clear';
}

/**
 * model: contextMemory · persisted · blobs · cross-reducers: plan, task.notificationDelivery, todo
 * owner: (unresolved)
 */
interface ContextUndoPayload {
  _name: 'context.undo';
  count: number;
}

/**
 * model: cron
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface CronAddPayload {
  _name: 'cron.add';
}

/**
 * model: cron
 * owner: (unresolved)
 */
interface CronCursorPayload {
  _name: 'cron.cursor';
  id: string;
  lastFiredAt: number;
}

/**
 * model: cron
 * owner: (unresolved)
 */
interface CronDeletePayload {
  _name: 'cron.delete';
  ids: string[];
}

/**
 * model: goal · persisted · cross-reducers: goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice
 * owner: (unresolved)
 */
interface ForkedPayload {
  _name: 'forked';
}

/**
 * model: fullCompaction · persisted · toEvent
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface FullCompactionBeginPayload {
  _name: 'full_compaction.begin';
}

/**
 * model: fullCompaction · persisted
 * owner: (unresolved)
 */
interface FullCompactionCancelPayload {
  _name: 'full_compaction.cancel';
}

/**
 * model: fullCompaction · persisted
 * owner: (unresolved)
 */
interface FullCompactionCompletePayload {
  _name: 'full_compaction.complete';
}

/**
 * model: goal · persisted · cross-reducers: goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice
 * owner: (unresolved)
 */
interface GoalClearPayload {
  _name: 'goal.clear';
}

/**
 * model: goal · persisted · cross-reducers: goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice, goalForkNotice
 * owner: (unresolved)
 */
interface GoalCreatePayload {
  _name: 'goal.create';
  goalId: string;
  objective: string;
  completionCriterion?: string;
  wallClockResumedAt?: number;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  actor?: 'user' | 'model' | 'runtime' | 'system';
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
}

/**
 * model: goal · persisted
 * owner: (unresolved)
 */
interface GoalUpdatePayload {
  _name: 'goal.update';
  goalId?: string;
  status?: 'active' | 'paused' | 'blocked' | 'complete';
  reason?: string;
  turnsUsed?: number;
  tokensUsed?: number;
  wallClockMs?: number;
  wallClockResumedAt?: number;
  budgetLimits?: {
    tokenBudget?: number;
    turnBudget?: number;
    wallClockBudgetMs?: number;
  };
  actor?: 'user' | 'model' | 'runtime' | 'system';
}

/**
 * model: interaction · persisted
 * owner: (unresolved)
 */
interface InteractionRequestPayload {
  _name: 'interaction.request';
  id: string;
  kind: 'approval' | 'question' | 'user_tool';
  toolCallId?: string;
  agentId?: string;
  request: any;
}

/**
 * model: interaction · persisted
 * owner: (unresolved)
 */
interface InteractionResolvedPayload {
  _name: 'interaction.resolved';
  id: string;
  response: any;
}

/**
 * model: interruptionReminder · persisted
 * owner: (unresolved)
 */
interface InterruptionReminderRecordedPayload {
  _name: 'interruptionReminder.recorded';
  turnId: number;
}

/**
 * model: llm.requestTrace · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface LlmRequestPayload {
  _name: 'llm.request';
}

/**
 * model: llm.requestTrace · persisted
 * owner: (unresolved)
 */
interface LlmToolsSnapshotPayload {
  _name: 'llm.tools_snapshot';
  hash: string;
  tools: {
    name: string;
    description: string;
    parameters: Record<string, any>;
  }[];
}

/**
 * model: mcp.discovery · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface McpToolsDiscoveredPayload {
  _name: 'mcp.tools_discovered';
}

/**
 * model: permissionRules · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface PermissionRecordApprovalResultPayload {
  _name: 'permission.record_approval_result';
}

/**
 * model: permissionRules
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface PermissionRulesAddPayload {
  _name: 'permission.rules.add';
}

/**
 * model: permissionMode · persisted · cross-reducers: permissionMode.configured
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface PermissionSetModePayload {
  _name: 'permission.set_mode';
}

/**
 * model: plan · persisted · toEvent
 * owner: (unresolved)
 */
interface PlanModeCancelPayload {
  _name: 'plan_mode.cancel';
  id?: string;
}

/**
 * model: plan · persisted · toEvent
 * owner: (unresolved)
 */
interface PlanModeEnterPayload {
  _name: 'plan_mode.enter';
  id: string;
}

/**
 * model: plan · persisted · toEvent
 * owner: (unresolved)
 */
interface PlanModeExitPayload {
  _name: 'plan_mode.exit';
  id?: string;
}

/**
 * model: plan · persisted · toEvent
 * owner: (unresolved)
 */
interface PlanRevisionPayload {
  _name: 'plan.revision';
  id: string;
  version: number;
  path: string;
  sha256: string;
  bytes: number;
}

/**
 * model: profile · persisted · cross-reducers: profile.activeTools
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ProfileBindPayload {
  _name: 'profile.bind';
}

/**
 * model: skill · toEvent
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface SkillActivatePayload {
  _name: 'skill.activate';
}

/**
 * model: swarm · persisted · toEvent
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface SwarmModeEnterPayload {
  _name: 'swarm_mode.enter';
}

/**
 * model: swarm · persisted · toEvent · cross-reducers: contextMemory
 * owner: (unresolved)
 */
interface SwarmModeExitPayload {
  _name: 'swarm_mode.exit';
}

/**
 * model: task · persisted · toEvent
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TaskStartedPayload {
  _name: 'task.started';
}

/**
 * model: task · persisted · toEvent
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TaskTerminatedPayload {
  _name: 'task.terminated';
}

/**
 * model: tokenCounting · toEvent
 * owner: (unresolved)
 */
interface TokenCountingMeasuredPayload {
  _name: 'token_counting.measured';
  length: number;
  tokens: number;
}

/**
 * model: tokenCounting · toEvent
 * owner: (unresolved)
 */
interface TokenCountingRebasedPayload {
  _name: 'token_counting.rebased';
  length: number;
  tokens: number;
  measured: boolean;
}

/**
 * model: tokenCounting · toEvent
 * owner: (unresolved)
 */
interface TokenCountingTruncatedPayload {
  _name: 'token_counting.truncated';
  length: number;
  tokens: number;
}

/**
 * model: userTool · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface ToolsRegisterUserToolPayload {
  _name: 'tools.register_user_tool';
}

/**
 * model: profile.activeTools · persisted
 * owner: (unresolved)
 */
interface ToolsResetActiveToolsPayload {
  _name: 'tools.reset_active_tools';
}

/**
 * model: profile.activeTools · persisted
 * owner: (unresolved)
 */
interface ToolsSetActiveToolsPayload {
  _name: 'tools.set_active_tools';
  names: string[];
}

/**
 * model: userTool · persisted
 * owner: (unresolved)
 */
interface ToolsUnregisterUserToolPayload {
  _name: 'tools.unregister_user_tool';
  name: string;
}

/**
 * model: todo · persisted
 * owner: (unresolved)
 */
interface ToolsUpdateStorePayload {
  _name: 'tools.update_store';
  key: string;
  value: any;
}

/**
 * model: turn · persisted · cross-reducers: interruptionReminder
 * owner: (unresolved)
 */
interface TurnCancelPayload {
  _name: 'turn.cancel';
  turnId?: number;
  target?: 'active' | 'queued';
  reason?: 'user_cancelled' | 'aborted';
}

/**
 * model: turn · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TurnEndedPayload {
  _name: 'turn.ended';
}

/**
 * model: turn · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TurnPromptPayload {
  _name: 'turn.prompt';
}

/**
 * model: turn · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface TurnSteerPayload {
  _name: 'turn.steer';
}

/**
 * model: usage · persisted
 * owner: (unresolved)
 * schema uses transforms; see the owner file
 */
interface UsageRecordPayload {
  _name: 'usage.record';
}

/** Record type → payload sketch. */
interface WirePayloadMap {
  "config.update": ConfigUpdatePayload;
  "context.append_loop_event": ContextAppendLoopEventPayload;
  "context.append_message": ContextAppendMessagePayload;
  "context.apply_compaction": ContextApplyCompactionPayload;
  "context.clear": ContextClearPayload;
  "context.undo": ContextUndoPayload;
  "cron.add": CronAddPayload;
  "cron.cursor": CronCursorPayload;
  "cron.delete": CronDeletePayload;
  "forked": ForkedPayload;
  "full_compaction.begin": FullCompactionBeginPayload;
  "full_compaction.cancel": FullCompactionCancelPayload;
  "full_compaction.complete": FullCompactionCompletePayload;
  "goal.clear": GoalClearPayload;
  "goal.create": GoalCreatePayload;
  "goal.update": GoalUpdatePayload;
  "interaction.request": InteractionRequestPayload;
  "interaction.resolved": InteractionResolvedPayload;
  "interruptionReminder.recorded": InterruptionReminderRecordedPayload;
  "llm.request": LlmRequestPayload;
  "llm.tools_snapshot": LlmToolsSnapshotPayload;
  "mcp.tools_discovered": McpToolsDiscoveredPayload;
  "permission.record_approval_result": PermissionRecordApprovalResultPayload;
  "permission.rules.add": PermissionRulesAddPayload;
  "permission.set_mode": PermissionSetModePayload;
  "plan_mode.cancel": PlanModeCancelPayload;
  "plan_mode.enter": PlanModeEnterPayload;
  "plan_mode.exit": PlanModeExitPayload;
  "plan.revision": PlanRevisionPayload;
  "profile.bind": ProfileBindPayload;
  "skill.activate": SkillActivatePayload;
  "swarm_mode.enter": SwarmModeEnterPayload;
  "swarm_mode.exit": SwarmModeExitPayload;
  "task.started": TaskStartedPayload;
  "task.terminated": TaskTerminatedPayload;
  "token_counting.measured": TokenCountingMeasuredPayload;
  "token_counting.rebased": TokenCountingRebasedPayload;
  "token_counting.truncated": TokenCountingTruncatedPayload;
  "tools.register_user_tool": ToolsRegisterUserToolPayload;
  "tools.reset_active_tools": ToolsResetActiveToolsPayload;
  "tools.set_active_tools": ToolsSetActiveToolsPayload;
  "tools.unregister_user_tool": ToolsUnregisterUserToolPayload;
  "tools.update_store": ToolsUpdateStorePayload;
  "turn.cancel": TurnCancelPayload;
  "turn.ended": TurnEndedPayload;
  "turn.prompt": TurnPromptPayload;
  "turn.steer": TurnSteerPayload;
  "usage.record": UsageRecordPayload;
}
