// apps/kimi-web/src/composables/useKimiWebClient.ts
// Thin facade — capability modules live under ./client/kimi-web-client/.

export type { Accent, ColorScheme } from "./client/useAppearance";
export type {
  ExtendedState,
  PromptAttachment,
} from "./client/kimi-web-client/types";
export type { ApprovalDecision, AppModel, AppProvider } from "../api/types";

import { ensureSessionTimeClock } from "./client/kimi-web-client/view-mappers";
import { initEnqueueEvent } from "./client/kimi-web-client/event-connection";
import { initChatProviders } from "./client/kimi-web-client/computed-chat";
import { initWorkspaceState } from "./client/kimi-web-client/bootstrap";
import {
  sideChat,
  modelProvider,
  workspaceState,
} from "./client/kimi-web-client/runtime";
import {
  workspace,
  sessions,
  activeSessionId,
  turns,
  tasks,
  activeAppTasks,
  todos,
  goal,
  swarms,
  swarmMembersByToolCallId,
  activationBadges,
  compaction,
  connection,
  loading,
  sessionLoading,
  loadingMoreMessages,
  hasMoreMessages,
  loadMoreMessagesError,
  serverVersion,
  dangerousBypassAuth,
  permission,
  thinking,
  planMode,
  swarmMode,
  goalMode,
  queued,
  warnings,
  questions,
  activity,
  turnActive,
  inFlight,
  working,
  isStartingFirstPrompt,
  skills,
  pendingApprovals,
  clearDangerousBypassAuth,
} from "./client/kimi-web-client/computed-chat";
import {
  workspacesView,
  visibleWorkspace,
  activeWorkspaceId,
  sessionsForView,
  workspaceGroups,
  attentionBySession,
  pendingBySession,
  attentionByWorkspace,
  unreadBySession,
  recentRoots,
  status,
  sessionCost,
  fileDiff,
  changes,
  gitInfo,
  gitDiffStats,
  activePullRequest,
  changesByPath,
  availableOpenInApps,
  authReady,
  defaultModel,
  managedProviderStatus,
  config,
  reorderWorkspaces,
  setWorkspaceSortMode,
  workspaceSortMode,
} from "./client/kimi-web-client/computed-workspace";
import {
  conversationToc,
  setConversationToc,
  onboarded,
  setOnboarded,
} from "./client/kimi-web-client/session-refresh";
import { appearance, notification, sound } from "./client/kimi-web-client/runtime";
import {
  selectedDiffPath,
  fileDiffLoading,
  initialized,
  connectIssue,
} from "./client/kimi-web-client/runtime";

let bootstrapped = false;
function ensureBootstrap(): void {
  if (bootstrapped) return;
  bootstrapped = true;
  initEnqueueEvent();
  initChatProviders();
  initWorkspaceState();
}

export function useKimiWebClient() {
  ensureBootstrap();
  ensureSessionTimeClock();

  return {
    workspace,
    sessions,
    activeSessionId,
    workspacesView,
    workspaceSortMode,
    visibleWorkspace,
    activeWorkspaceId,
    sessionsForView,
    workspaceGroups,
    attentionBySession,
    pendingBySession,
    attentionByWorkspace,
    unreadBySession,
    recentRoots,
    turns,
    tasks,
    activeAppTasks,
    todos,
    goal,
    swarms,
    swarmMembersByToolCallId,
    activationBadges,
    compaction,
    status,
    sessionCost,
    fileDiff,
    selectedDiffPath,
    fileDiffLoading,
    changes,
    gitInfo,
    gitDiffStats,
    activePullRequest,
    changesByPath,
    pendingApprovals,
    availableOpenInApps,
    connection,
    loading,
    sessionLoading,
    loadingMoreMessages,
    hasMoreMessages,
    loadMoreMessagesError,
    serverVersion,
    dangerousBypassAuth,
    clearDangerousBypassAuth,
    initialized,
    connectIssue,
    permission,
    thinking,
    planMode,
    swarmMode,
    goalMode,
    queued,
    warnings,
    questions,
    activity,
    turnActive,
    inFlight,
    working,
    isStartingFirstPrompt,
    fastMoon: appearance.fastMoon,
    models: modelProvider!.models,
    starredModelIds: modelProvider!.starredModelIds,
    providers: modelProvider!.providers,
    uiFontSize: appearance.uiFontSize,
    setUiFontSize: appearance.setUiFontSize,
    conversationToc,
    setConversationToc,
    colorScheme: appearance.colorScheme,
    setColorScheme: appearance.setColorScheme,
    accent: appearance.accent,
    setAccent: appearance.setAccent,
    notifyOnComplete: notification.notifyOnComplete,
    notifyOnQuestion: notification.notifyOnQuestion,
    notifyOnApproval: notification.notifyOnApproval,
    notifyPermission: notification.notifyPermission,
    setNotifyOnComplete: notification.setNotifyOnComplete,
    setNotifyOnQuestion: notification.setNotifyOnQuestion,
    setNotifyOnApproval: notification.setNotifyOnApproval,
    soundOnComplete: sound.soundOnComplete,
    setSoundOnComplete: sound.setSoundOnComplete,
    onboarded,
    setOnboarded,
    load: workspaceState!.load,
    selectSession: workspaceState!.selectSession,
    clearActiveSession: workspaceState!.clearActiveSession,
    loadOlderMessages: workspaceState!.loadOlderMessages,
    loadWorkspaces: workspaceState!.loadWorkspaces,
    loadMoreSessions: workspaceState!.loadMoreSessions,
    loadAllSessions: workspaceState!.loadAllSessions,
    selectWorkspace: workspaceState!.selectWorkspace,
    openWorkspace: workspaceState!.openWorkspace,
    openWorkspaceDraft: workspaceState!.openWorkspaceDraft,
    startSessionAndSendPrompt: workspaceState!.startSessionAndSendPrompt,
    startSessionAndActivateSkill: workspaceState!.startSessionAndActivateSkill,
    startSessionAndOpenSideChat: workspaceState!.startSessionAndOpenSideChat,
    addWorkspaceByPath: workspaceState!.addWorkspaceByPath,
    browseFs: workspaceState!.browseFs,
    getFsHome: workspaceState!.getFsHome,
    sendPrompt: workspaceState!.sendPrompt,
    steerPrompt: workspaceState!.steerPrompt,
    sideChatVisible: sideChat!.sideChatVisible,
    sideChatSessionId: sideChat!.sideChatSessionId,
    sideChatTurns: sideChat!.sideChatTurns,
    sideChatRunning: sideChat!.sideChatRunning,
    sideChatSending: sideChat!.sideChatSending,
    openSideChat: sideChat!.openSideChat,
    closeSideChat: sideChat!.closeSideChat,
    sendSideChatPrompt: sideChat!.sendSideChatPrompt,
    uploadImage: workspaceState!.uploadImage,
    abortCurrentPrompt: workspaceState!.abortCurrentPrompt,
    respondApproval: workspaceState!.respondApproval,
    respondQuestion: workspaceState!.respondQuestion,
    dismissQuestion: workspaceState!.dismissQuestion,
    pendingQuestionActions: workspaceState!.pendingQuestionActions,
    pendingApprovalActions: workspaceState!.pendingApprovalActions,
    cancelTask: workspaceState!.cancelTask,
    setPermission: workspaceState!.setPermission,
    setThinking: modelProvider!.setThinking,
    setPlanMode: workspaceState!.setPlanMode,
    togglePlanMode: workspaceState!.togglePlanMode,
    setSwarmMode: workspaceState!.setSwarmMode,
    toggleSwarmMode: workspaceState!.toggleSwarmMode,
    setGoalMode: workspaceState!.setGoalMode,
    toggleGoalMode: workspaceState!.toggleGoalMode,
    createGoal: workspaceState!.createGoal,
    controlGoal: workspaceState!.controlGoal,
    enqueue: workspaceState!.enqueue,
    dismissWarning: workspaceState!.dismissWarning,
    renameSession: workspaceState!.renameSession,
    renameWorkspace: workspaceState!.renameWorkspace,
    deleteWorkspace: workspaceState!.deleteWorkspace,
    reorderWorkspaces,
    setWorkspaceSortMode,
    archiveSession: workspaceState!.archiveSession,
    exportSession: workspaceState!.exportSession,
    restoreSession: workspaceState!.restoreSession,
    loadArchivedSessions: workspaceState!.loadArchivedSessions,
    compact: workspaceState!.compact,
    forkSession: workspaceState!.forkSession,
    undo: workspaceState!.undo,
    unqueue: workspaceState!.unqueue,
    reorderQueue: workspaceState!.reorderQueue,
    searchFiles: workspaceState!.searchFiles,
    loadGitStatus: workspaceState!.loadGitStatus,
    loadFileDiff: workspaceState!.loadFileDiff,
    clearFileDiff: workspaceState!.clearFileDiff,
    listDir: workspaceState!.listDir,
    readFileContent: workspaceState!.readFileContent,
    getFileDownloadUrl: workspaceState!.getFileDownloadUrl,
    openWorkspaceFile: workspaceState!.openWorkspaceFile,
    openInApp: workspaceState!.openInApp,
    revealWorkspaceFile: workspaceState!.revealWorkspaceFile,
    resolveImageUrl: workspaceState!.resolveImageUrl,
    loadModels: modelProvider!.loadModels,
    loadProviders: modelProvider!.loadProviders,
    skills,
    activateSkill: modelProvider!.activateSkill,
    setModel: modelProvider!.setModel,
    toggleStarModel: modelProvider!.toggleStarModel,
    addProvider: modelProvider!.addProvider,
    deleteProvider: modelProvider!.deleteProvider,
    refreshProvider: modelProvider!.refreshProvider,
    refreshAllProviders: modelProvider!.refreshAllProviders,
    authReady,
    defaultModel,
    managedProviderStatus,
    config,
    updateConfig: workspaceState!.updateConfig,
    checkAuth: workspaceState!.checkAuth,
    startOAuthLogin: modelProvider!.startOAuthLogin,
    pollOAuthLogin: modelProvider!.pollOAuthLogin,
    cancelOAuthLogin: modelProvider!.cancelOAuthLogin,
    logout: workspaceState!.logout,
  };
}
